# Generated by Django 5.1.2 on 2024-10-27 14:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='staff',
            name='resumptionDate',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='vacationDate',
        ),
        migrations.AddField(
            model_name='staff',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstName',
            field=models.CharField(help_text='First name', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastName',
            field=models.CharField(help_text='Last name (Surname)', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='middleName',
            field=models.CharField(blank=True, help_text='Middle name', max_length=50),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftType', models.CharField(choices=[('ms', 'Morning shift'), ('as', 'Afternoon shift')], help_text='Shift type', max_length=32)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='roster.day')),
                ('staffs', models.ManyToManyField(related_name='shifts', to='roster.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffRosterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Active')),
                ('vacationDate', models.DateField(blank=True, help_text='Resumption date', null=True)),
                ('resumptionDate', models.DateField(blank=True, help_text='Resumption date', null=True)),
                ('group', models.IntegerField(validators=[django.core.validators.MinValueValidator])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffAssignments', to='roster.roster')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosterAssignments', to='roster.staff')),
            ],
        ),
    ]
